version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    labels:
      - ci-cd
      - dependencies
    commit-message:
      prefix: ci
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    labels:
      - dependencies
    commit-message:
      prefix: npm
